@extends('admin::customer-portal.layouts.app', ['title' => 'Invoice '.$invoice->invoice_number, 'subtitle' => $invoice->subject ?: 'Final invoice and payment details.'])

@section('content')
    @php
        $money = fn ($value) => \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($value);
        $qty = fn ($value) => \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::decimal($value);
        $charges = app(\Webkul\Core\Support\DocumentChargeManager::class)->extract($invoice, 'proforma');
    @endphp
    <div class="mb-4 flex justify-end"><a class="primary-button inline-flex items-center gap-2" href="{{ route('customer_portal.invoices.pdf', $invoice->id) }}"><span class="icon-download"></span> Download PDF</a></div>
    <div class="grid gap-4 md:grid-cols-2">
        <section class="portal-card p-5"><p class="portal-kicker">Invoice summary</p><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-xs text-gray-500">Invoice #</dt><dd class="mt-1 font-semibold dark:text-white">{{ $invoice->invoice_number }}</dd></div><div><dt class="text-xs text-gray-500">Status</dt><dd class="mt-1">@include('admin::customer-portal.partials.status-badge', ['status' => $invoice->status])</dd></div><div><dt class="text-xs text-gray-500">Proforma #</dt><dd class="mt-1 dark:text-white">{{ $invoice->proformaInvoice?->proforma_number ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Issue date</dt><dd class="mt-1 dark:text-white">{{ $invoice->issue_date?->format('Y-m-d') ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Due date</dt><dd class="mt-1 dark:text-white">{{ $invoice->due_date?->format('Y-m-d') ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Customer PO</dt><dd class="mt-1 dark:text-white">{{ $invoice->customer_po_reference ?: '-' }}</dd></div></dl></section>
        <section class="portal-card p-5"><p class="portal-kicker">Payment summary</p><div class="mt-4 space-y-3 text-sm"><div class="flex justify-between dark:text-gray-300"><span>Invoice total</span><strong>{{ $money($invoice->grand_total) }}</strong></div><div class="flex justify-between text-green-700"><span>Advance applied</span><strong>- {{ $money($invoice->advance_applied) }}</strong></div><div class="flex justify-between text-green-700"><span>Payments received</span><strong>- {{ $money($invoice->received_amount) }}</strong></div><div class="flex justify-between border-t border-gray-200 pt-3 text-base font-semibold dark:border-gray-800 dark:text-white"><span>Balance due</span><span>{{ $money($invoice->remaining_amount) }}</span></div></div></section>
    </div>
    <section class="portal-card mt-4 overflow-hidden"><div class="border-b border-gray-200 px-5 py-4 dark:border-gray-800"><p class="portal-kicker">Line items</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-gray-200 bg-slate-50 text-xs uppercase text-gray-500 dark:border-gray-800 dark:bg-gray-950"><tr><th class="px-4 py-3">Item code</th><th class="px-4 py-3">Description</th><th class="px-4 py-3">Color</th><th class="px-4 py-3 text-right">Qty</th><th class="px-4 py-3 text-right">Rate</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-gray-200 dark:divide-gray-800">@foreach($invoice->items as $item)<tr class="portal-row"><td class="px-4 py-3 font-semibold dark:text-white">{{ $item->item_code ?: '-' }}</td><td class="px-4 py-3 dark:text-gray-300">{{ $item->item_name }}</td><td class="px-4 py-3 dark:text-gray-300">{{ $item->color_variant_name ?: '-' }}</td><td class="px-4 py-3 text-right dark:text-gray-300">{{ $qty($item->qty) }}</td><td class="px-4 py-3 text-right dark:text-gray-300">{{ $money($item->unit_price) }}</td><td class="px-4 py-3 text-right font-semibold dark:text-white">{{ $money($item->line_total) }}</td></tr>@endforeach</tbody></table></div></section>
    <div class="mt-4 grid gap-4 md:grid-cols-2"><section class="portal-card p-5"><p class="portal-kicker">Advance receipts</p><div class="mt-4 space-y-2">@forelse($invoice->proformaInvoice?->receipts ?? [] as $receipt)<div class="flex justify-between rounded-md border border-gray-200 p-3 text-sm dark:border-gray-700"><span class="dark:text-gray-300">{{ $receipt->receipt_number }} | {{ $receipt->payment_date?->format('Y-m-d') }}</span><strong class="text-green-700">{{ $money($receipt->amount) }}</strong></div>@empty<p class="text-sm text-gray-500">No advance receipts.</p>@endforelse</div></section><section class="portal-card p-5"><p class="portal-kicker">Invoice payment receipts</p><div class="mt-4 space-y-2">@forelse($invoice->receipts as $receipt)<div class="flex justify-between rounded-md border border-gray-200 p-3 text-sm dark:border-gray-700"><span class="dark:text-gray-300">{{ $receipt->receipt_number }} | {{ $receipt->payment_date?->format('Y-m-d') }}</span><strong class="text-green-700">{{ $money($receipt->amount) }}</strong></div>@empty<p class="text-sm text-gray-500">No subsequent payments.</p>@endforelse</div></section></div>
@endsection
