@extends('admin::customer-portal.layouts.app', ['title' => 'Proforma '.$proforma->proforma_number, 'subtitle' => $proforma->subject ?: 'Invoice values, product details, and recorded receipts.'])

@section('content')
    @php
        $chargeManager = app(\Webkul\Core\Support\DocumentChargeManager::class);
        $charges = $chargeManager->extract($proforma, 'proforma');
        $addressLines = fn ($value) => collect(preg_split("/\r\n|\n|\r/", trim((string) data_get($value, 'address'))))->map(fn ($line) => trim($line))->filter();
        $billingLines = $addressLines($proforma->billing_address);
        $shippingLines = $addressLines($proforma->shipping_address);
    @endphp

    <div class="mb-4 flex flex-wrap justify-end gap-2"><a class="primary-button inline-flex items-center gap-2" href="{{ route('customer_portal.proformas.pdf', $proforma->id) }}"><span class="icon-download"></span> Download PDF</a>@if($proforma->attachment_path)<a class="secondary-button inline-flex items-center gap-2" href="{{ route('customer_portal.proformas.attachment', $proforma->id) }}"><span class="icon-attachment"></span> Attachment</a>@endif</div>

    <div class="grid gap-4 md:grid-cols-2"><section class="portal-card p-5"><p class="portal-kicker">Document Summary</p><h2 class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">Proforma information</h2><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-xs text-gray-500">Proforma #</dt><dd class="mt-1 font-semibold text-gray-900 dark:text-white">{{ $proforma->proforma_number }}</dd></div><div><dt class="text-xs text-gray-500">Status</dt><dd class="mt-1">@include('admin::customer-portal.partials.status-badge', ['status' => $proforma->status])</dd></div><div><dt class="text-xs text-gray-500">Quote #</dt><dd class="mt-1 text-gray-800 dark:text-gray-200">{{ $proforma->quote?->quote_number ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Issue Date</dt><dd class="mt-1 text-gray-800 dark:text-gray-200">{{ $proforma->issue_date?->format('Y-m-d') ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Payment Term</dt><dd class="mt-1 text-gray-800 dark:text-gray-200">{{ $proforma->payment_term ?: '-' }}</dd></div></dl></section><section class="portal-card p-5"><p class="portal-kicker">Commercial Details</p><h2 class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">Order and payment information</h2><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-xs text-gray-500">Sales Owner</dt><dd class="mt-1 text-gray-800 dark:text-gray-200">{{ $proforma->salesOwner?->name ?: '-' }}</dd></div><div><dt class="text-xs text-gray-500">Grand Total</dt><dd class="mt-1 font-semibold text-gray-900 dark:text-white">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->grand_total) }}</dd></div><div><dt class="text-xs text-gray-500">Advance Received</dt><dd class="mt-1 font-semibold text-green-700 dark:text-green-300">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->received_amount) }}</dd></div><div><dt class="text-xs text-gray-500">Remaining Balance</dt><dd class="mt-1 font-semibold text-amber-700 dark:text-amber-300">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->remaining_amount) }}</dd></div></dl></section></div>

    <div class="mt-4 grid gap-4 md:grid-cols-2">@foreach([['title' => 'Bill To', 'lines' => $billingLines, 'fallback' => collect([$organization->billing_street, collect([$organization->billing_city, $organization->billing_state, $organization->billing_postcode, $organization->billing_country])->filter()->implode(', ')])->filter()], ['title' => 'Ship To', 'lines' => $shippingLines, 'fallback' => collect([$organization->shipping_street, collect([$organization->shipping_city, $organization->shipping_state, $organization->shipping_postcode, $organization->shipping_country])->filter()->implode(', ')])->filter()]] as $address)<section class="portal-card p-5"><p class="portal-kicker">{{ $address['title'] }}</p><h2 class="mt-1 font-semibold text-gray-900 dark:text-white">{{ $organization->name }}</h2><div class="mt-3 space-y-1 text-sm text-gray-700 dark:text-gray-300">@forelse($address['lines']->isNotEmpty() ? $address['lines'] : $address['fallback'] as $line)<p>{{ $line }}</p>@empty<p class="text-gray-500">No address available.</p>@endforelse</div></section>@endforeach</div>

    <section class="portal-card mt-4 overflow-hidden"><div class="border-b border-gray-200 px-5 py-4 dark:border-gray-800"><p class="portal-kicker">Proforma Invoice Items</p><h2 class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">Products and pricing</h2></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="border-b border-gray-200 bg-slate-50 text-xs font-semibold uppercase text-gray-500 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-300"><tr><th class="w-20 px-4 py-3">Image</th><th class="px-4 py-3">Item Code</th><th class="px-4 py-3">Product Name</th><th class="px-4 py-3">Color</th><th class="px-4 py-3 text-right">Qty</th><th class="px-4 py-3">Unit</th><th class="px-4 py-3 text-right">Rate</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-gray-200 text-sm dark:divide-gray-800">
        @forelse($proforma->items as $item)<tr class="portal-row"><td class="px-4 py-3">@if($item->preview_image)<img src="{{ $item->preview_image }}" alt="{{ $item->item_name }}" class="h-12 w-12 rounded-md border border-gray-200 object-cover dark:border-gray-700">@else<span class="flex h-12 w-12 items-center justify-center rounded-md border border-gray-200 bg-slate-50 dark:border-gray-700 dark:bg-gray-950"><i class="icon-image text-xl text-gray-300"></i></span>@endif</td><td class="px-4 py-3 font-semibold text-gray-900 dark:text-white">{{ $item->item_code ?: '-' }}</td><td class="px-4 py-3"><p class="font-medium text-gray-900 dark:text-white">{{ $item->item_name ?: '-' }}</p><p class="mt-0.5 max-w-[280px] text-xs text-gray-500">{{ $item->description }}</p></td><td class="px-4 py-3 text-gray-700 dark:text-gray-300">{{ $item->color_variant_name ?: '-' }}</td><td class="px-4 py-3 text-right text-gray-700 dark:text-gray-300">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::decimal($item->qty) }}</td><td class="px-4 py-3 text-gray-700 dark:text-gray-300">{{ $item->unit ?: 'PCS' }}</td><td class="px-4 py-3 text-right text-gray-700 dark:text-gray-300">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($item->unit_price) }}</td><td class="px-4 py-3 text-right font-semibold text-gray-900 dark:text-white">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($item->line_total) }}</td></tr>@empty @include('admin::customer-portal.partials.table-empty', ['colspan' => 8, 'message' => 'No line items available.']) @endforelse
    </tbody></table></div></section>

    <div class="mt-4 grid gap-4 md:grid-cols-2"><section class="portal-card p-5"><p class="portal-kicker">Totals</p><div class="mt-4 grid gap-3 text-sm"><div class="flex justify-between text-gray-700 dark:text-gray-300"><span>Items Total</span><span>{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->subtotal) }}</span></div>@foreach($charges as $charge)<div class="flex justify-between text-gray-700 dark:text-gray-300"><span>{{ $charge['name'] ?? 'Charge' }}</span><span>{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($charge['amount']) }}</span></div>@endforeach<div class="flex justify-between text-gray-700 dark:text-gray-300"><span>Grand Total</span><span>{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->grand_total) }}</span></div><div class="flex justify-between text-green-700 dark:text-green-300"><span>Advance Received</span><span>{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->received_amount) }}</span></div><div class="flex justify-between border-t border-gray-200 pt-3 text-base font-semibold text-gray-900 dark:border-gray-800 dark:text-white"><span>Remaining Balance</span><span>{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($proforma->remaining_amount) }}</span></div></div></section><section class="portal-card p-5"><p class="portal-kicker">Receipt History</p><div class="mt-4 grid gap-2">@forelse($proforma->receipts as $receipt)<div class="rounded-md border border-gray-200 p-3 dark:border-gray-700"><div class="flex items-center justify-between gap-3"><div><p class="text-sm font-semibold text-gray-900 dark:text-white">{{ $receipt->receipt_number ?: 'Receipt' }}</p><p class="mt-1 text-xs text-gray-500">{{ $receipt->payment_date?->format('Y-m-d') ?: '-' }} | {{ $receipt->payment_method ?: 'Method not set' }}</p></div><p class="font-semibold text-gray-900 dark:text-white">{{ \Webkul\Admin\Http\Controllers\CustomerPortal\PortalController::money($receipt->amount) }}</p></div></div>@empty<p class="text-sm text-gray-500">No advance receipts recorded yet.</p>@endforelse</div></section></div>
    <div class="mt-4 grid gap-4 md:grid-cols-2"><section class="portal-card p-5"><p class="portal-kicker">Remarks</p><p class="mt-3 whitespace-pre-line text-sm text-gray-700 dark:text-gray-300">{{ $proforma->notes ?: '-' }}</p></section><section class="portal-card p-5"><p class="portal-kicker">Terms & Conditions</p><p class="mt-3 whitespace-pre-line text-sm text-gray-700 dark:text-gray-300">{{ $proforma->terms ?: '-' }}</p></section></div>
@endsection
